### PR TITLE
WASI support

### PR DESCRIPTION
**Pull request by calebschoepp**
## Motivation 
I was attempting to use this library with a WASI target and it was not compiling. The cfg options in the Cargo.toml and the source files did not match. See #146.

## Solution

Fix cfg options to match.

### CODE REVIEW

**Review by djc — APPROVED** [review]
This looks reasonable to me, thanks!

**Comment by djc** [comment]
Can this target be tested in CI? Would be good to avoid regressions.

**Comment by calebschoepp** [comment]
@djc we could perhaps add another job to `CI.yaml` similar to:
```yaml
  test-build-wasm:
    name: build tests (wasm)
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        target: wasm32-unknown-unknown
    - name: build all tests
      run: cargo test --no-run
```

I have no familiarity with your CI though so not too sure.

**Comment by djc** [comment]
That looks like a good start, could you add that in?

**Comment by djc** [comment]
Thanks! Going to publish this in #142.

**Comment by calebschoepp** [comment]
@djc thanks for all the reviews and work on this library 👍

**Pull request merged**
